#include "fmt/extended_types.h"

#ifndef FMT_INSTANCIATE_TEMPLATE
#error "FMT_INSTANCIATE_TEMPLATE needs to be defined"
#endif

#ifdef FMT_INSTANCIATE_INTEGRAL
#undef FMT_INSTANCIATE_INTEGRAL
FMT_INSTANCIATE_TEMPLATE(signed char);
FMT_INSTANCIATE_TEMPLATE(unsigned char);
FMT_INSTANCIATE_TEMPLATE(short);
FMT_INSTANCIATE_TEMPLATE(unsigned short);
FMT_INSTANCIATE_TEMPLATE(int);
FMT_INSTANCIATE_TEMPLATE(unsigned int);
FMT_INSTANCIATE_TEMPLATE(long);
FMT_INSTANCIATE_TEMPLATE(unsigned long);
FMT_INSTANCIATE_TEMPLATE(long long);
FMT_INSTANCIATE_TEMPLATE(unsigned long long);

#ifdef FMT_INT128_SUPPORT
FMT_INSTANCIATE_TEMPLATE(FmtInt128);
FMT_INSTANCIATE_TEMPLATE(FmtUInt128);
#endif // FMT_INT128_SUPPORT

#endif // FMT_INSTANCIATE_INTEGRAL

#ifdef FMT_INSTANCIATE_FLOATING_POINT
#undef FMT_INSTANCIATE_FLOATING_POINT

#ifdef FMT_FLOAT16_SUPPORT
FMT_INSTANCIATE_TEMPLATE(FmtFloat16);
#endif // FMT_FLOAT16_SUPPORT

#ifdef FMT_BFLOAT16_SUPPORT
FMT_INSTANCIATE_TEMPLATE(FmtBFloat16);
#endif // FMT_BFLOAT16_SUPPORT

FMT_INSTANCIATE_TEMPLATE(float);
FMT_INSTANCIATE_TEMPLATE(double);
FMT_INSTANCIATE_TEMPLATE(long double);

#ifdef FMT_FLOAT80_SUPPORT
FMT_INSTANCIATE_TEMPLATE(FmtFloat80);
#endif // FMT_FLOAT80_SUPPORT

#ifdef FMT_FLOAT128_SUPPORT
FMT_INSTANCIATE_TEMPLATE(FmtFloat128);
#endif // FMT_FLOAT128_SUPPORT

#endif // FMT_INSTANCIATE_FLOATING_POINT
