#ifndef FMT_INSTANCIATE_TEMPLATE
#error "FMT_INSTANCIATE_TEMPLATE needs to be defined"
#endif

#ifdef FMT_INSTANCIATE_INTEGRAL
#undef FMT_INSTANCIATE_INTEGRAL
FMT_INSTANCIATE_TEMPLATE(signed char);
FMT_INSTANCIATE_TEMPLATE(unsigned char);
FMT_INSTANCIATE_TEMPLATE(short);
FMT_INSTANCIATE_TEMPLATE(unsigned short);
FMT_INSTANCIATE_TEMPLATE(int);
FMT_INSTANCIATE_TEMPLATE(unsigned int);
FMT_INSTANCIATE_TEMPLATE(long);
FMT_INSTANCIATE_TEMPLATE(unsigned long);
FMT_INSTANCIATE_TEMPLATE(long long);
FMT_INSTANCIATE_TEMPLATE(unsigned long long);

#endif // FMT_INSTANCIATE_INTEGRAL

#ifdef FMT_INSTANCIATE_FLOATING_POINT
#undef FMT_INSTANCIATE_FLOATING_POINT
FMT_INSTANCIATE_TEMPLATE(float);
FMT_INSTANCIATE_TEMPLATE(double);

#endif // FMT_INSTANCIATE_FLOATING_POINT
