#include "fmt/extended_types.h"

#ifndef FMT_INSTANCIATE_TEMPLATE
#error "FMT_INSTANCIATE_TEMPLATE needs to be defined"
#endif

#ifdef FMT_INSTANCIATE_INTEGRAL
#undef FMT_INSTANCIATE_INTEGRAL
FMT_INSTANCIATE_TEMPLATE(signed char);
FMT_INSTANCIATE_TEMPLATE(unsigned char);
FMT_INSTANCIATE_TEMPLATE(short);
FMT_INSTANCIATE_TEMPLATE(unsigned short);
FMT_INSTANCIATE_TEMPLATE(int);
FMT_INSTANCIATE_TEMPLATE(unsigned int);
FMT_INSTANCIATE_TEMPLATE(long);
FMT_INSTANCIATE_TEMPLATE(unsigned long);
FMT_INSTANCIATE_TEMPLATE(long long);
FMT_INSTANCIATE_TEMPLATE(unsigned long long);

#ifdef FMT_INT128_SUPPORT
FMT_INSTANCIATE_TEMPLATE(fmt_int128_t);
FMT_INSTANCIATE_TEMPLATE(fmt_uint128_t);

#endif // FMT_INT128_SUPPORT

#endif // FMT_INSTANCIATE_INTEGRAL

#ifdef FMT_INSTANCIATE_FLOATING_POINT
#undef FMT_INSTANCIATE_FLOATING_POINT
FMT_INSTANCIATE_TEMPLATE(float);
FMT_INSTANCIATE_TEMPLATE(double);

#ifdef FMT_FLOAT16_SUPPORT
FMT_INSTANCIATE_TEMPLATE(fmt_float16_t);

#endif // FMT_FLOAT16_SUPPORT

#ifdef FMT_BFLOAT16_SUPPORT
FMT_INSTANCIATE_TEMPLATE(fmt_bfloat16_t);

#endif // FMT_BFLOAT16_SUPPORT

#ifdef FMT_FLOAT128_SUPPORT
FMT_INSTANCIATE_TEMPLATE(fmt_float128_t);

#endif // FMT_FLOAT128_SUPPORT

#endif // FMT_INSTANCIATE_FLOATING_POINT
