#ifndef INSTANCIATE_TEMPLATE
#error "INSTANCIATE_TEMPLATE needs to be defined"
#endif

#ifdef INSTANCIATE_INTEGRAL
#undef INSTANCIATE_INTEGRAL
INSTANCIATE_TEMPLATE(char);
INSTANCIATE_TEMPLATE(signed char);
INSTANCIATE_TEMPLATE(unsigned char);
INSTANCIATE_TEMPLATE(short);
INSTANCIATE_TEMPLATE(unsigned short);
INSTANCIATE_TEMPLATE(int);
INSTANCIATE_TEMPLATE(unsigned int);
INSTANCIATE_TEMPLATE(long);
INSTANCIATE_TEMPLATE(unsigned long);
INSTANCIATE_TEMPLATE(long long);
INSTANCIATE_TEMPLATE(unsigned long long);

#endif // INSTANCIATE_INTEGRAL

#ifdef INSTANCIATE_FLOATING_POINT
#undef INSTANCIATE_FLOATING_POINT
INSTANCIATE_TEMPLATE(float);
INSTANCIATE_TEMPLATE(double);

#endif // INSTANCIATE_FLOATING_POINT
