name: CMake Build

on: [push]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/Example
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake (Debug)
      run: cmake . -G"Unix Makefiles" -B"build" -DCMAKE_BUILD_TYPE=Debug

    - name: Build (Debug)
      run: cmake --build build

    - name: Execute (Debug)
      run: '(./build/Example || ([[ `./build/Example | tail -n1` == "Assertion failed: "* ]] && echo "Fails as expected")) || false'

    - name: Configure CMake (Release)
      run: cmake . -G"Unix Makefiles" -B"build" -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release)
      run: cmake --build build

    - name: Execute (Release)
      run: ./build/Example
